### ISSUE TITLE
请问你在使用ant组件时有没有遇到样式覆盖问题？

### ISSUE THREAD

**Issue by zhh877644371** [HeavenSky/react-ant#1]

**Comment by zhh877644371** [comment]
我也是按照砖家大大的框架来学习，正常情况下应该是这样的样式
![image](https://user-images.githubusercontent.com/17739760/34148847-f294c96c-e4dd-11e7-8c29-79dd3a510700.png)
我添加了一个引用Table组件的页面，然后在加载组件后变成了这样的样式：
![image](https://user-images.githubusercontent.com/17739760/34148882-11d632f2-e4de-11e7-9879-3c2b86210cf3.png)
你有遇到过这样的问题吗？

**Comment by HeavenSky** [comment]
不好意思啊，这么晚才来回复，之前没去github的issue里看，关于样式覆盖问题，你的问题应该是 a 标签的样式被 ant design覆盖，这里需要注意一点的是 ant design 改写了css全局的字体样式,a标签的全局样式， 再就是ant design这样做没什么不好，他的字体兼容MAC windows Linux ，所以如果你需要特殊样式，可以加class自己另写一套样式覆盖antd的就好，同理 a 标签也是

**Comment by HeavenSky** [comment]
如果你还是不想用antd的样式，那么建议你使用antd的按需引入（这个不一定有效，也可能会出现覆盖的问题），或者将他的css下载下来自己改写了，当然这些都比较麻烦，还是建议考虑如果是自己特殊需求，那么自己给容器加一个class，然后写上自己的样式覆盖原本的就行
